"""Try except block is used to continue the execution of the program even after a runtime error has occured"""
print("Enter num 1")
num_1 = input()
print("Enter num 2")
num_2 = input()
try:
    print("The sum of two numbers is",int(num_1)+int(num_2))
except Exception as e:
    print(e) 

print("This line is very important")
